### ISSUE TITLE
global: nested transaction inside task

### ISSUE THREAD

**Issue by krzysztof** [inveniosoftware/invenio-webhooks#20]
Does this task need to use nested transaction and then commit?

https://github.com/inveniosoftware/invenio-webhooks/blob/master/invenio_webhooks/models.py#L146-L150

I think nested transaction is unnecessary. If the task is running outside celery, the nested transaction can act as a safe mechanism, but then, if it's running outside celery it would also flush current db session, which would create all sorts of strange behaviours, not occuring in production anyway.

**Comment by lnielsen** [comment]
it can be replaced with a try/except rollback

**Comment by krzysztof** [comment]
My question was more about consistency.
Should tasks be written such that they work both on single-thread as well as celery? If so nested transaction is as good as try/except rollback. And then we have a lot of tests to fix all across the modules :)

I would suggest assuming otherwise, i.e. that tasks are always independent of current session, and pay special attention to this in testing...

**Comment by lnielsen** [comment]
> Should tasks be written such that they work both on single-thread as well as celery?

No. Task should always be written with the assumption that they are run asynchronously (i.e. production will never set ``CELERY_ALWAYS_EAGER`` to true).

**Comment by krzysztof** [comment]
Then I believe the ``nested_transaction`` should be removed and everything else stays as is.

**Comment by lnielsen** [comment]
This:

```python
with db.session.begin_nested():
    # …
db.session.commit()
```

or this

```python
try:
    # …
    db.session.commit()
except Exception:
    db.session.rollback()

```
but not:

```python
# …
db.session.commit()
```

Otherwise you leave a failed transaction behind AFAIK

**Comment by krzysztof** [comment]
I think it's not a problem since when the celery task thread ends the session should be cleaned anyway:

"However, the scope of transactions themselves, i.e. ending them via Session.commit() or Session.rollback(), will usually still be something that must be explicitly arranged for at the appropriate time, **unless the application actually ties the lifespan of a thread to the lifespan of a transaction.**"
(http://docs.sqlalchemy.org/en/latest/orm/contextual.html#thread-local-scope)

**Comment by krzysztof** [comment]
I guess this requires some careful study before we agree on any standard practice for writing tasks.

**Comment by jirikuncar** [comment]
IMHO this will not harm anybody and it's safe in case transactions are handled differently by Celery app.

```python
with db.session.begin_nested():
    # …
db.session.commit()
```
