### ISSUE TITLE
models: improper status response

### ISSUE THREAD

**Issue by omelkonian** [inveniosoftware/invenio-webhooks#40]
Regarding the status metadata propagation from the Event REST API:(https://github.com/inveniosoftware/invenio-webhooks/blob/master/invenio_webhooks/models.py#L176-L181)

The state metadata from the Celery backend should not be propagated only when the state is `PENDING`, because:

1. If `CELERY_TRACK_STARTED` is set, then the state will always be `STARTED ` whenever a meaningful status update occurs.
2. We should allow custom states to expose their status metadata.

Moreover, I think we should not expose only `meta['message']`, but the whole dictionary (e.g. when you do not have access to the code that updates the status).

**Comment by omelkonian** [comment]
@jirikuncar I cannot think of any other useful information to add.

**Comment by jirikuncar** [comment]
> Moreover, I think we should not expose only `meta['message']`, but the whole dictionary (e.g. when you do not have access to the code that updates the status).

We have discussed it with @egabancho who confirmed that only minimal information should be transferred in headers while the task is running. For more advanced progress updates the new Invenio-SSE should be used.
